version: '3.8'

services:
  # Meilisearch 服务
  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: meilisearch
    ports:
      - "7750:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-your_master_key_here}
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - meilisearch-network

  # Embedding Proxy 服务
  embedding_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: meilisearch-embedding-proxy:latest
    container_name: embedding_proxy
    ports:
      - "8000:8000"
    environment:
      # 必需的环境变量 - 请设置您的 API 密钥
      - API_KEY=${API_KEY}
      
      # 可选的环境变量 (有默认值)
      - BASE_URL=${BASE_URL:-https://api.siliconflow.cn/v1}
      - MODEL_NAME=${MODEL_NAME:-BAAI/bge-large-zh-v1.5}
      - MAX_TOKEN_LIMIT=${MAX_TOKEN_LIMIT:-10000}
      - EMBEDDING_DIMENSIONS=${EMBEDDING_DIMENSIONS:-1024}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TIMEOUT=${TIMEOUT:-30}
      
      # Meilisearch 配置
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_API_KEY=${MEILI_MASTER_KEY:-your_master_key_here}
      - SERVICE_URL=http://embedding_proxy:8000
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 重启策略
    restart: unless-stopped
    
    # 依赖 Meilisearch 服务
    depends_on:
      meilisearch:
        condition: service_healthy
    
    networks:
      - meilisearch-network

# 数据卷
volumes:
  meilisearch_data:
    driver: local

# 网络配置
networks:
  meilisearch-network:
    driver: bridge
